# Source: https://github.com/microsoft/vscode-dev-containers/blob/master/containers/javascript-node/.devcontainer/Dockerfile
ARG VARIANT=14
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:${VARIANT}
