name: NetOffice Documentation Build

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: |
        yarn install
      env:
        CI: true
    - name: Build Website
      run: |
        gulp default
      env:
        CI: true
    - name: Create Artifact
      uses: actions/upload-artifact@v3
      with:
        name: netoffice-documentation-website
        path: dist
